### ISSUE TITLE
Question about combining tags

### ISSUE THREAD

**Issue by Stefanhg** [scastlara/pytest-tagging#11]
Hello,

I got a case where I would like the tags to be combined into a new tag.  The case I got is that I have many testcases and instead of having to add a new tag to each testsuite if a new tag is made I could just create a list of tags to run.

**Example:**
```
# test_tags.py
@pytest.mark.tags("tag1")
def test_tag1():
    pass
    
@pytest.mark.tags("tag2")
def test_tag2():
    pass

@pytest.mark.tags("tag3")
def test_tag3():
    pass
    
# conftest.py
tag1_tag2 = ["tag1", "tag2"]  # tag3 is not included
```

Here tag1_tag2 is the tags I would like to run with --tags tag1_tag2 
Is it possible in any way to do this with the current version of pytest-tagging? Like running a `pytest.mark.add_tags("tag1_tag2", tag1_tag2)` in my conftest or do you have an idea to a way it could be done with a PR?

**Comment by scastlara** [comment]
Hey! I suppose you can save each tag into a variable, and then create a small utility function that merged them however you like?

Then you could:

```python
purest.mark.tags(combine(TAG_1, TAG2))
def test...
```

That is if I am understanding you correctly, of course 😀

**Comment by Stefanhg** [comment]
It is not what I am aiming for. 
These examples simply just results in the same as just adding an additional tag to each testcase.

What I am aiming for is being able to combine tags in a single file. So If I have different groups of testsuites/classes/tags then It then can be combined into a single tag called "All"

Example:
I got a tags called: `clickable_links, pictures, open_new_tap` and i also got a tag called `clickable_buttons`
I then want to include all tags except in a new tag called `all` with the exception of `clickable_buttons`

**Example:**

```
@pytest.mark.tags("clickable_links")
class TestsClickableLinks:
...
@pytest.mark.tags("pictures"
class TestsPictures:
...
@pytest.mark.tags("open_new_tap")
class TestsOpenNewTap:
...
@pytest.mark.tags("clickable_buttons")
class TestsClickableButtons:
...
```

Then in my conftest I then in some way combine the tags:
```
import pytest_tagging
pytest_tagging.combine_tags("all", ["clickable_links", "pictures", "clickable_buttons")
```

So here when i do `pytest --tags all` it will run all tests within the `all `tag

**Comment by Stefanhg** [comment]
I will maybe look into it.
I still can't figure out if this is the way I wanna go with this.
