### ISSUE TITLE
Add support for showing all tags available

### ISSUE THREAD

**Issue by Stefanhg** [scastlara/pytest-tagging#12]
Hello.
It would be nice to make a way for showing all the available tags. 
It could simply just be if `--tags` is empty, it will show the available tags

**Comment by scastlara** [comment]
Sure! I'll do it when I find the time (unless you want to do it of course).

Out of curiosity, are you using this plugin?

**Comment by Stefanhg** [comment]
Thanks!
I may look into it soon.

I am not using it currently as the company I work at is working on converting to pytest and I am in charge of the research and development of needed plugins.
But in the future we have chosen this as the plugin we will use for our testruns so therefore we will be using it a lot!
