### ISSUE TITLE
pytest --tags (tag) does no work with --collect-only

### ISSUE THREAD

**Issue by Stefanhg** [scastlara/pytest-tagging#14]
When `pytest --tags my_tag --collect-only` it does not include the selected tests.
It might be a part of the collection logic or priority as I assume collection hook is still executed for `--collect-only`.

I'll take a look at it.

**Comment by Stefanhg** [comment]
Awaiting reply on https://github.com/pytest-dev/pytest/discussions/11846
--collect-only is not implemented with the standard hooks or argparse and therefore can be hard to modify.

**Comment by Stefanhg** [comment]
Hello @scastlara,
Is there a reason why the plugin is only registered when you don't use `--collect-only`?
In the `pytest_configure `function it will only register the plugin if you are not collecting items.

**Comment by scastlara** [comment]
> Hello @scastlara,
> 
> Is there a reason why the plugin is only registered when you don't use `--collect-only`?
> 
> In the `pytest_configure `function it will only register the plugin if you are not collecting items.

Mmmm probably because I did not want to do unnecessary stuff if we are only collecting? Is it necessary or useful to register the plugin when we collect? We can change it if so.

**Comment by Stefanhg** [comment]
@scastlara Ah okay, yeah I do actually need it. I actually though it was a bug in PyTest that didn't allow me to do this.
Because I cannot combine --collect-only and --tags because of this. 
That means I cannot see what tests will be executed with a tag specified.

**Comment by scastlara** [comment]
Let me know if it works now and if so we can close this!

**Comment by Stefanhg** [comment]
@scastlara Approved! It works just as expected!
