### ISSUE TITLE
Add the ability to negate the tag at startup

### ISSUE THREAD

**Issue by pomponchik** [scastlara/pytest-tagging#16]
Hello!

We use your library, thank you very much, it helps a lot.

There is one feature request: add the ability to specify when running tests those tags that tests should not be run with.

An example:

```bash
pytest --tags mobile --no-tags flaky --tags-operand AND
```

In this example, we are running tests marked with the `mobile` tag that do not have the `flaky` tag.

**Comment by scastlara** [comment]
Hey! Happy to see you find it useful!

Your feature request makes sense. Are you interested in submitting a pull request?

**Comment by scastlara** [comment]
It is not clear to me how one would resolve the operand over the `--no-tags` option and the `--tags` option. Some possibilities:

1. Operand applies only to `--tags`, and `--no-tags` simply takes precedence.
2. Operand applies to both `--tags` and `--no-tags`, which means that you can do more complex operations, but lose a bit of control.

Given

```sh
pytest --tags mobile --tags iOS --no-tags flaky --tags-operand AND
```

- **Option 1** would run tests with tags `mobile` AND `iOS`, but without any test that has the tag `flaky`.
- **Option 2** would run tests with tags `mobile` AND `iOS` AND `flaky` (?).

Option 1 seems more useful to me.

**Comment by scastlara** [comment]
Implemented Option 1 from above with `--exclude-tags`. Feel fee to reopen or create a new issue if you feel that does not cover your needs.
