### ISSUE TITLE
Release 1.4.2 breaks tests with no tags specified

### ISSUE THREAD

**Issue by Stefanhg** [scastlara/pytest-tagging#19]
When no tags are specified no tests are being executed. 
I checked out the selected_items and deselected_items and both are empty.
Seems to be related to if statement line 116

Looking into issue.

**Comment by Stefanhg** [comment]
Reproduced with testcase:

```
def test_no_tags(pytester):
    """Test that with no tags specified a test is still executed"""
    pytester.makepyfile("def test_pass(): pass")
    res = pytester.runpytest()
    res.assert_outcomes(passed=1)
```

**Comment by scastlara** [comment]
Thanks for the issue and for the fix! Had to copy it over to another PR (https://github.com/scastlara/pytest-tagging/pull/21) to fix the lints and release, since I could not fetch or push to your branch.

Please, re-open if this is still an issue!

**Comment by Stefanhg** [comment]
@scastlara I think you should have permissions now.
