### ISSUE TITLE
Would you mind making this package compatible with Python 3.8?

### ISSUE THREAD

**Issue by zhuwenxing** [scastlara/pytest-tagging#23]
Hi, thanks for this great package.

I previously used the package https://github.com/Projectplace/pytest-tags, but it has not been published to PyPI and is no longer maintained. I tried your package and it seems to be compatible. However, pytest-tagging (https://github.com/scastlara/pytest-tagging) requires Python >= 3.10, and due to certain reasons, my project will be stuck with Python 3.8 for a long time, so I cannot install this package. I tried modifying the Poetry configuration locally to >= 3.8, and the package can be built successfully, so I was wondering if it's possible to make this package compatible with Python 3.8?

**Comment by scastlara** [comment]
It is perfectly possible. Would you be interested in making a pull request?

**Comment by zhuwenxing** [comment]
> It is perfectly possible. Would you be interested in making a pull request?

PR is open

**Comment by scastlara** [comment]
Thank you for your contribution! New version was just released to PyPi. If you encounter any problem, please feel free to open another issue!
