### ISSUE TITLE
Support for pytest>=8

### ISSUE THREAD

**Issue by Stefanhg** [scastlara/pytest-tagging#26]
Hello,
I got reminded about this tool being capped to pytest 7. 
Was there a reason for not having pytest 8 support?  I ran all tests on newest pytest version and they all passed.

**Comment by scastlara** [comment]
Hey! No reason at all I think! If it works the version range should be changed and we should test the plugin with it.

**Comment by scastlara** [comment]
Feel free to make a PR, otherwise this weekend I will get around it and do it.

**Comment by scastlara** [comment]
Just published a new version relaxing pytest requirements (no need to be so picky with the ranges here).
Thanks for reporting!
